// <auto-generated />
using System;
using cs_third_party_web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cs_third_party_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cs_third_party_web.Models.AttendanceLog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("device_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("device_identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("log_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("person_identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("person_name")
                        .HasColumnType("longtext");

                    b.Property<string>("project_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("attendance_logs");
                });
#pragma warning restore 612, 618
        }
    }
}
